apiVersion: demo.example.com/v1
kind: Echo
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-controller
    app.kubernetes.io/managed-by: kustomize
  name: echo-sample
spec:
  # TODO(user): Add fields here
